export const PRODUCTS_REQUEST= "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS= "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL= "PRODUCTS_FAIL";

export const SINGLE_PRODUCTS_REQUEST= "SINGLE_PRODUCTS_REQUEST";
export const SINGLE_PRODUCTS_SUCCESS= "SINGLE_PRODUCTS_SUCCESS";
export const SINGLE_PRODUCTS_FAIL= "SINGLE_PRODUCTS_FAIL";


export const NEW_REVIEW_REQUEST= "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS= "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET= "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL= "NEW_REVIEW_FAIL";



export const CLEAR_ERROR= "CLEAR_ERROR";