export const LOGIN_REQUEST= "LOGIN_REQUEST";
export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";
export const REGISTER_REQUEST= "REGISTER_REQUEST";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAIL= "REGISTER_FAIL";

export const LOADING_USER_REQUEST= "LOADING_USER_REQUEST";
export const LOADING_USER_SUCCESS= "LOADING_USER_SUCCESS";
export const LOADING_USER_FAIL= "LOADING_USER_FAIL";


export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const LOGOUT_FAIL= "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST= "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET= "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST= "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS= "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET= "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL= "UPDATE_PASSWORD_FAIL";

export const CLEAR_ERROR= "CLEAR_ERROR";