export const LOGIN_REQUEST= "LOGIN_REQUEST";
export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";
export const REGISTER_REQUEST= "REGISTER_REQUEST";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAIL= "REGISTER_FAIL";

export const LOADING_USER_REQUEST= "LOADING_USER_REQUEST";
export const LOADING_USER_SUCCESS= "LOADING_USER_SUCCESS";
export const LOADING_USER_FAIL= "LOADING_USER_FAIL";


export const CLEAR_ERROR= "CLEAR_ERROR";